package org.scheming.salary.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.scheming.salary.entity.User;
import org.scheming.salary.entity.Salary;
import org.scheming.salary.entity.Project;
import org.scheming.salary.entity.Allowance;
import org.scheming.salary.entity.Attendance;

import org.scheming.salary.dao.UserDao;
import org.scheming.salary.dao.SalaryDao;
import org.scheming.salary.dao.ProjectDao;
import org.scheming.salary.dao.AllowanceDao;
import org.scheming.salary.dao.AttendanceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig salaryDaoConfig;
    private final DaoConfig projectDaoConfig;
    private final DaoConfig allowanceDaoConfig;
    private final DaoConfig attendanceDaoConfig;

    private final UserDao userDao;
    private final SalaryDao salaryDao;
    private final ProjectDao projectDao;
    private final AllowanceDao allowanceDao;
    private final AttendanceDao attendanceDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        salaryDaoConfig = daoConfigMap.get(SalaryDao.class).clone();
        salaryDaoConfig.initIdentityScope(type);

        projectDaoConfig = daoConfigMap.get(ProjectDao.class).clone();
        projectDaoConfig.initIdentityScope(type);

        allowanceDaoConfig = daoConfigMap.get(AllowanceDao.class).clone();
        allowanceDaoConfig.initIdentityScope(type);

        attendanceDaoConfig = daoConfigMap.get(AttendanceDao.class).clone();
        attendanceDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        salaryDao = new SalaryDao(salaryDaoConfig, this);
        projectDao = new ProjectDao(projectDaoConfig, this);
        allowanceDao = new AllowanceDao(allowanceDaoConfig, this);
        attendanceDao = new AttendanceDao(attendanceDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Salary.class, salaryDao);
        registerDao(Project.class, projectDao);
        registerDao(Allowance.class, allowanceDao);
        registerDao(Attendance.class, attendanceDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        salaryDaoConfig.getIdentityScope().clear();
        projectDaoConfig.getIdentityScope().clear();
        allowanceDaoConfig.getIdentityScope().clear();
        attendanceDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public SalaryDao getSalaryDao() {
        return salaryDao;
    }

    public ProjectDao getProjectDao() {
        return projectDao;
    }

    public AllowanceDao getAllowanceDao() {
        return allowanceDao;
    }

    public AttendanceDao getAttendanceDao() {
        return attendanceDao;
    }

}
