package org.scheming.salary.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ATTENDANCE".
 */
public class Attendance {

    private Long id;
    private Integer business_leave;
    private Integer sick_leave;
    private Integer late;
    private Integer leave_early;
    private Integer absenteeism;
    private Long salary;

    public Attendance() {
    }

    public Attendance(Long id) {
        this.id = id;
    }

    public Attendance(Long id, Integer business_leave, Integer sick_leave, Integer late, Integer leave_early, Integer absenteeism, Long salary) {
        this.id = id;
        this.business_leave = business_leave;
        this.sick_leave = sick_leave;
        this.late = late;
        this.leave_early = leave_early;
        this.absenteeism = absenteeism;
        this.salary = salary;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getBusiness_leave() {
        return business_leave;
    }

    public void setBusiness_leave(Integer business_leave) {
        this.business_leave = business_leave;
    }

    public Integer getSick_leave() {
        return sick_leave;
    }

    public void setSick_leave(Integer sick_leave) {
        this.sick_leave = sick_leave;
    }

    public Integer getLate() {
        return late;
    }

    public void setLate(Integer late) {
        this.late = late;
    }

    public Integer getLeave_early() {
        return leave_early;
    }

    public void setLeave_early(Integer leave_early) {
        this.leave_early = leave_early;
    }

    public Integer getAbsenteeism() {
        return absenteeism;
    }

    public void setAbsenteeism(Integer absenteeism) {
        this.absenteeism = absenteeism;
    }

    public Long getSalary() {
        return salary;
    }

    public void setSalary(Long salary) {
        this.salary = salary;
    }

}
