package org.scheming.salary.entity;

import org.scheming.salary.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import org.scheming.salary.dao.SalaryItemDao;
import org.scheming.salary.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SALARY_ITEM".
 */
public class SalaryItem {

    private Long id;
    private Integer current_month;
    private Float borrow;
    private Float cut_payment;
    private Float personal_social_security;
    private Long salary_item;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient SalaryItemDao myDao;

    private User salary_user_relation;
    private Long salary_user_relation__resolvedKey;


    public SalaryItem() {
    }

    public SalaryItem(Long id) {
        this.id = id;
    }

    public SalaryItem(Long id, Integer current_month, Float borrow, Float cut_payment, Float personal_social_security, Long salary_item) {
        this.id = id;
        this.current_month = current_month;
        this.borrow = borrow;
        this.cut_payment = cut_payment;
        this.personal_social_security = personal_social_security;
        this.salary_item = salary_item;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getSalaryItemDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCurrent_month() {
        return current_month;
    }

    public void setCurrent_month(Integer current_month) {
        this.current_month = current_month;
    }

    public Float getBorrow() {
        return borrow;
    }

    public void setBorrow(Float borrow) {
        this.borrow = borrow;
    }

    public Float getCut_payment() {
        return cut_payment;
    }

    public void setCut_payment(Float cut_payment) {
        this.cut_payment = cut_payment;
    }

    public Float getPersonal_social_security() {
        return personal_social_security;
    }

    public void setPersonal_social_security(Float personal_social_security) {
        this.personal_social_security = personal_social_security;
    }

    public Long getSalary_item() {
        return salary_item;
    }

    public void setSalary_item(Long salary_item) {
        this.salary_item = salary_item;
    }

    /** To-one relationship, resolved on first access. */
    public User getSalary_user_relation() {
        Long __key = this.salary_item;
        if (salary_user_relation__resolvedKey == null || !salary_user_relation__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            UserDao targetDao = daoSession.getUserDao();
            User salary_user_relationNew = targetDao.load(__key);
            synchronized (this) {
                salary_user_relation = salary_user_relationNew;
            	salary_user_relation__resolvedKey = __key;
            }
        }
        return salary_user_relation;
    }

    public void setSalary_user_relation(User salary_user_relation) {
        synchronized (this) {
            this.salary_user_relation = salary_user_relation;
            salary_item = salary_user_relation == null ? null : salary_user_relation.getId();
            salary_user_relation__resolvedKey = salary_item;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
