package org.scheming.salary.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private java.util.Date join_date;
    private float base_salary;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String name, java.util.Date join_date, float base_salary) {
        this.id = id;
        this.name = name;
        this.join_date = join_date;
        this.base_salary = base_salary;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public java.util.Date getJoin_date() {
        return join_date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setJoin_date(java.util.Date join_date) {
        this.join_date = join_date;
    }

    public float getBase_salary() {
        return base_salary;
    }

    public void setBase_salary(float base_salary) {
        this.base_salary = base_salary;
    }

}
